// lib/questions.ts
import type { Question } from './types'

export const QUESTIONS: Question[] = [
  // === TIER 1: CORE PERSONALITY ===

  // Openness (3 questions)
  { id: '', code: 'O_01', text: 'I enjoy exploring abstract ideas and concepts.', type: 'likert', dimension: 'openness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'O_02', text: 'I prefer concrete, practical tasks over theoretical ones.', type: 'likert', dimension: 'openness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'O_03', text: 'When given free time, which would you rather do?', type: 'forced_choice', dimension: 'openness', tier: 1, options: { a: 'Read about a familiar topic I know well', b: 'Explore a completely new subject I know nothing about' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Conscientiousness (3 questions)
  { id: '', code: 'C_01', text: 'I complete tasks thoroughly, even when no one is watching.', type: 'likert', dimension: 'conscientiousness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'C_02', text: 'How often do you follow through on commitments you make to yourself?', type: 'frequency', dimension: 'conscientiousness', tier: 1, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'C_03', text: 'I tend to leave tasks unfinished when they become difficult.', type: 'likert', dimension: 'conscientiousness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 3, is_active: true },

  // Extraversion (3 questions)
  { id: '', code: 'E_01', text: 'Social gatherings energize rather than drain me.', type: 'likert', dimension: 'extraversion', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'E_02', text: 'After a long day of meetings, I feel:', type: 'forced_choice', dimension: 'extraversion', tier: 1, options: { a: 'Drained and need quiet time alone', b: 'Energized and ready for more conversation' }, weight: 1.2, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'E_03', text: 'How often do you initiate conversations with people you don\'t know?', type: 'frequency', dimension: 'extraversion', tier: 1, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Agreeableness (3 questions)
  { id: '', code: 'A_01', text: 'I find it easy to see situations from other people\'s perspectives.', type: 'likert', dimension: 'agreeableness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'A_02', text: 'I prioritize team harmony even when I disagree with the direction.', type: 'likert', dimension: 'agreeableness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'A_03', text: 'Your team disagrees with your recommendation. You:', type: 'situational', dimension: 'agreeableness', tier: 1, options: { scenario: 'Your team strongly disagrees with your recommendation.', choices: ['A: Stand firm — you\'ve done the analysis', 'B: Find a compromise that partially addresses both views', 'C: Defer to the team — consensus matters more', 'D: Escalate to leadership to decide'], scores: [1, 3.7, 5, 2.3] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Emotional Stability (3 questions)
  { id: '', code: 'ES_01', text: 'I remain calm when things go wrong unexpectedly.', type: 'likert', dimension: 'emotional_stability', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'ES_02', text: 'I worry about making mistakes even after the fact.', type: 'likert', dimension: 'emotional_stability', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'ES_03', text: 'How quickly do you recover emotionally from a setback at work?', type: 'frequency', dimension: 'emotional_stability', tier: 1, options: { labels: ['Very Slowly (days)','Slowly','Moderately','Quickly','Very Quickly (hours)'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 3, is_active: true },

  // Honesty-Humility (3 questions)
  { id: '', code: 'HH_01', text: 'I avoid taking credit for outcomes that involved significant help from others.', type: 'likert', dimension: 'honesty_humility', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'HH_02', text: 'I would bend rules slightly if I was confident no one would find out.', type: 'likert', dimension: 'honesty_humility', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'HH_03', text: 'Which matters more to you?', type: 'forced_choice', dimension: 'honesty_humility', tier: 1, options: { a: 'Being seen as successful and impressive', b: 'Acting with integrity even when it costs you' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === TIER 2: COGNITIVE ARCHITECTURE ===

  // Cognitive Agility (3 questions)
  { id: '', code: 'CA_01', text: 'I enjoy switching between different types of problems rapidly.', type: 'likert', dimension: 'cognitive_agility', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CA_02', text: 'You have 60 seconds to decide which abstract pattern completes the sequence:', type: 'timed', dimension: 'cognitive_agility', tier: 2, options: { scenario: 'Rank the options by how logically they complete the pattern: Circle-Square-Triangle-?', choices: ['A: Pentagon (adds sides)', 'B: Circle (repeats first)', 'C: Star (breaks pattern)', 'D: Hexagon (adds sides differently)'], scores: [5, 2.3, 1, 3.7] }, weight: 1.3, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CA_03', text: 'When facing a complex problem, I naturally break it into components.', type: 'likert', dimension: 'cognitive_agility', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 3, is_active: true },

  // Executive Function (3 questions)
  { id: '', code: 'EF_01', text: 'I can keep multiple competing priorities organized without losing track.', type: 'likert', dimension: 'executive_function', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'EF_02', text: 'How often do you start a task but get pulled to another before finishing?', type: 'frequency', dimension: 'executive_function', tier: 2, options: { labels: ['Almost Always','Usually','Sometimes','Rarely','Almost Never'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'EF_03', text: 'You have 3 deadlines tomorrow and an unexpected crisis today. You:', type: 'timed', dimension: 'executive_function', tier: 2, options: { scenario: 'Three deadlines tomorrow, unexpected crisis today.', choices: ['A: Handle the crisis first, then work late on deadlines', 'B: Triage — delegate the crisis, protect the most critical deadline', 'C: Communicate delays proactively, focus on the crisis', 'D: Push through all simultaneously'], scores: [2.3, 5, 3.7, 1] }, weight: 1.3, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Attention Control (3 questions)
  { id: '', code: 'AC_01', text: 'I can focus deeply for hours without needing breaks.', type: 'likert', dimension: 'attention_control', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'AC_02', text: 'Notifications and interruptions significantly disrupt my concentration.', type: 'likert', dimension: 'attention_control', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'AC_03', text: 'How often do you achieve a state of deep focus (flow) at work?', type: 'frequency', dimension: 'attention_control', tier: 2, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Systems Thinking (3 questions)
  { id: '', code: 'ST_01', text: 'When analyzing a problem, I naturally consider second and third-order effects.', type: 'likert', dimension: 'systems_thinking', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'ST_02', text: 'I find it easy to identify the root cause of complex organizational problems.', type: 'likert', dimension: 'systems_thinking', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'ST_03', text: 'Rank these approaches to solving a recurring team problem:', type: 'rank_order', dimension: 'systems_thinking', tier: 2, options: { items: ['Map the system to find root cause', 'Fix the immediate symptom quickly', 'Ask why 5 times before acting', 'Try multiple solutions in parallel'], target_item_index: 0 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Creative Intelligence (3 questions)
  { id: '', code: 'CI_01', text: 'I regularly make unexpected connections between unrelated fields.', type: 'likert', dimension: 'creative_intelligence', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CI_02', text: 'When brainstorming, I generate more ideas than I could ever use.', type: 'likert', dimension: 'creative_intelligence', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CI_03', text: 'Which visual pattern feels most natural to your thinking style?', type: 'visual', dimension: 'creative_intelligence', tier: 2, options: { images: ['visual_q1_a.svg','visual_q1_b.svg','visual_q1_c.svg','visual_q1_d.svg'], scores: [3, 5, 1, 4] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === TIER 3: MOTIVATIONAL DNA ===

  // Achievement Drive (3 questions)
  { id: '', code: 'AD_01', text: 'I push myself to exceed expectations, not just meet them.', type: 'likert', dimension: 'achievement_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'AD_02', text: 'Allocate 100 points across what motivates you most at work:', type: 'allocation', dimension: 'achievement_drive', tier: 3, options: { items: ['Achieving excellence', 'Being liked by colleagues', 'Financial reward', 'Making an impact'], total: 100, target_item_index: 0 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'AD_03', text: 'I feel restless when I\'m not working toward a challenging goal.', type: 'likert', dimension: 'achievement_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 3, is_active: true },

  // Risk Tolerance (3 questions)
  { id: '', code: 'RT_01', text: 'I would rather pursue a 30% chance at $100K than a guaranteed $25K.', type: 'likert', dimension: 'risk_tolerance', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'RT_02', text: 'A promising startup offers you equity + lower base salary. Your current job is stable. You:', type: 'situational', dimension: 'risk_tolerance', tier: 3, options: { scenario: 'A promising startup offers equity + lower salary vs your stable current job.', choices: ['A: Decline — stability is more valuable', 'B: Ask for more data before deciding', 'C: Negotiate a transition period, then join', 'D: Join immediately — upside is worth it'], scores: [1, 2.3, 3.7, 5] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'RT_03', text: 'How often do you make significant decisions with incomplete information?', type: 'frequency', dimension: 'risk_tolerance', tier: 3, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 3, is_active: true },

  // Autonomy Need (3 questions)
  { id: '', code: 'AN_01', text: 'I do my best work when I have full control over how I approach a task.', type: 'likert', dimension: 'autonomy_need', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'AN_02', text: 'Frequent check-ins and status updates help me stay on track.', type: 'likert', dimension: 'autonomy_need', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'AN_03', text: 'Which working structure do you prefer?', type: 'forced_choice', dimension: 'autonomy_need', tier: 3, options: { a: 'Clear expectations, regular feedback, team accountability', b: 'Open mandate, self-directed priorities, minimal oversight' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Purpose Orientation (3 questions)
  { id: '', code: 'PO_01', text: 'I need my work to contribute to something larger than personal gain.', type: 'likert', dimension: 'purpose_orientation', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'PO_02', text: 'Allocate 100 points across what you\'d want your legacy to reflect:', type: 'allocation', dimension: 'purpose_orientation', tier: 3, options: { items: ['Making a meaningful difference', 'Building wealth', 'Achieving recognition', 'Mastering a craft'], total: 100, target_item_index: 0 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'PO_03', text: 'A high-paying job with no clear social impact would feel unfulfilling to me.', type: 'likert', dimension: 'purpose_orientation', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Competitive Drive (3 questions)
  { id: '', code: 'CD_01', text: 'Knowing others are ahead of me motivates me to work harder.', type: 'likert', dimension: 'competitive_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CD_02', text: 'I keep track of how my performance compares to peers and benchmarks.', type: 'frequency', dimension: 'competitive_drive', tier: 3, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CD_03', text: 'Winning matters more to me than just participating.', type: 'likert', dimension: 'competitive_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === TIER 4: BEHAVIORAL EXPRESSION ===

  // Social Influence (3 questions)
  { id: '', code: 'SI_01', text: 'I naturally take the lead in group discussions.', type: 'likert', dimension: 'social_influence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'SI_02', text: 'People often adopt my recommendations without much persuasion.', type: 'likert', dimension: 'social_influence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'SI_03', text: 'Rank your preferred approach to getting buy-in from stakeholders:', type: 'rank_order', dimension: 'social_influence', tier: 4, options: { items: ['Present data and let it speak', 'Tell a compelling story', 'Build relationships first', 'Make it their idea'], target_item_index: 1 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Conflict Navigation (3 questions)
  { id: '', code: 'CN_01', text: 'I address disagreements directly rather than avoiding them.', type: 'likert', dimension: 'conflict_navigation', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CN_02', text: 'A colleague publicly criticizes your work in a meeting. You:', type: 'situational', dimension: 'conflict_navigation', tier: 4, options: { scenario: 'A colleague publicly criticizes your work during a team meeting.', choices: ['A: Stay silent — address it privately later', 'B: Calmly defend your work with evidence in the moment', 'C: Ask clarifying questions to understand their concern', 'D: Acknowledge the critique and commit to improvement'], scores: [1, 5, 3.7, 2.3] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CN_03', text: 'I find it uncomfortable to push back on someone senior to me.', type: 'likert', dimension: 'conflict_navigation', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 3, is_active: true },

  // Communication Style (3 questions)
  { id: '', code: 'CS_01', text: 'I prefer data-backed arguments over emotionally resonant stories.', type: 'likert', dimension: 'communication_style', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CS_02', text: 'When presenting, I lead with the human story rather than the metrics.', type: 'likert', dimension: 'communication_style', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CS_03', text: 'Which visual pattern feels most natural to your communication style?', type: 'visual', dimension: 'communication_style', tier: 4, options: { images: ['visual_q2_a.svg','visual_q2_b.svg','visual_q2_c.svg','visual_q2_d.svg'], scores: [1, 3, 5, 4] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Collaboration Signature (3 questions)
  { id: '', code: 'CO_01', text: 'I produce my best work independently rather than in groups.', type: 'likert', dimension: 'collaboration_signature', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'CO_02', text: 'Allocate 100 points across your preferred working modes:', type: 'allocation', dimension: 'collaboration_signature', tier: 4, options: { items: ['Solo deep work', 'Collaborative team sessions', 'Pair/duo work', 'Large group workshops'], total: 100, target_item_index: 1 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'CO_03', text: 'I feel more productive in a team environment than working alone.', type: 'likert', dimension: 'collaboration_signature', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === TIER 5: LEADERSHIP & CAREER ===

  // Leadership Drive (3 questions)
  { id: '', code: 'LD_01', text: 'I naturally step up to lead when a group lacks direction.', type: 'likert', dimension: 'leadership_drive', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'LD_02', text: 'I prefer being in a position where I set direction rather than execute it.', type: 'likert', dimension: 'leadership_drive', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'LD_03', text: 'Rank your preference for role in a new initiative:', type: 'rank_order', dimension: 'leadership_drive', tier: 5, options: { items: ['Lead it — set vision and strategy', 'Execute it — deliver with excellence', 'Advise it — provide expertise', 'Support it — enable others to succeed'], target_item_index: 0 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Strategic Orientation (3 questions)
  { id: '', code: 'SO_01', text: 'I think in years and decades rather than weeks and months.', type: 'likert', dimension: 'strategic_orientation', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'SO_02', text: 'I get more energy from defining where we\'re going than from optimizing current operations.', type: 'likert', dimension: 'strategic_orientation', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'SO_03', text: 'A competitor launches a superior product. You prioritize:', type: 'situational', dimension: 'strategic_orientation', tier: 5, options: { scenario: 'A competitor just launched a superior product in your market.', choices: ['A: Respond tactically — improve your current product quickly', 'B: Reframe the market — position around a different dimension', 'C: Analyze long-term — is this category worth winning?', 'D: Accelerate roadmap — execute planned strategy faster'], scores: [1, 3.7, 5, 2.3] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Specialist-Generalist (2 questions)
  { id: '', code: 'SG_01', text: 'I prefer going very deep in one domain over being broadly competent across many.', type: 'likert', dimension: 'specialist_generalist', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'SG_02', text: 'Which do you find more valuable in your career so far?', type: 'forced_choice', dimension: 'specialist_generalist', tier: 5, options: { a: 'Developing deep expertise in my core domain', b: 'Building diverse skills across many domains' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },

  // Innovation Index (3 questions)
  { id: '', code: 'II_01', text: 'I am drawn to problems that have no established solutions.', type: 'likert', dimension: 'innovation_index', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'II_02', text: 'I get frustrated when teams resist new approaches in favor of "how we\'ve always done it."', type: 'likert', dimension: 'innovation_index', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'II_03', text: 'Which visual pattern most represents your approach to innovation?', type: 'visual', dimension: 'innovation_index', tier: 5, options: { images: ['visual_q3_a.svg','visual_q3_b.svg','visual_q3_c.svg','visual_q3_d.svg'], scores: [2, 5, 3, 1] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === TIER 6: RESILIENCE & GROWTH ===

  // Psychological Resilience (3 questions)
  { id: '', code: 'PR_01', text: 'After a major failure, I recover and try again relatively quickly.', type: 'likert', dimension: 'psychological_resilience', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'PR_02', text: 'Your most important project fails publicly. You:', type: 'situational', dimension: 'psychological_resilience', tier: 6, options: { scenario: 'Your most important project fails publicly and visibly.', choices: ['A: Withdraw temporarily to process and recover', 'B: Immediately analyze what went wrong and share learnings', 'C: Reframe it as a stepping stone and move forward', 'D: Double down — find a way to salvage or rebuild'], scores: [1, 3.7, 5, 2.3] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'PR_03', text: 'I use setbacks as learning opportunities more than as sources of discouragement.', type: 'likert', dimension: 'psychological_resilience', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 3, is_active: true },

  // Growth Mindset (3 questions)
  { id: '', code: 'GM_01', text: 'I believe my core abilities can be substantially developed with effort.', type: 'likert', dimension: 'growth_mindset', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'GM_02', text: 'How often do you deliberately seek out difficult challenges to grow?', type: 'frequency', dimension: 'growth_mindset', tier: 6, options: { labels: ['Almost Never','Rarely','Sometimes','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'GM_03', text: 'Which do you believe more strongly?', type: 'forced_choice', dimension: 'growth_mindset', tier: 6, options: { a: 'People have a natural ceiling on how much they can change', b: 'With the right approach, anyone can develop almost any skill' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Adaptability Quotient (3 questions)
  { id: '', code: 'AQ_01', text: 'I thrive in rapidly changing environments.', type: 'likert', dimension: 'adaptability_quotient', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'AQ_02', text: 'Unexpected pivots in direction energize rather than frustrate me.', type: 'likert', dimension: 'adaptability_quotient', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'AQ_03', text: 'Rank these scenarios by how comfortable you\'d feel:', type: 'rank_order', dimension: 'adaptability_quotient', tier: 6, options: { items: ['Your role scope doubles unexpectedly', 'Your team restructures with a new manager', 'Your company pivots to a new market', 'Your project scope is cut in half'], target_item_index: 2 }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // Learning Agility (3 questions)
  { id: '', code: 'LA_01', text: 'I can become reasonably proficient at a new skill within weeks.', type: 'likert', dimension: 'learning_agility', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'LA_02', text: 'How quickly do you typically feel productive in a completely new domain?', type: 'frequency', dimension: 'learning_agility', tier: 6, options: { labels: ['Very Slowly (months)','Slowly','Moderately','Quickly','Very Quickly (weeks)'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 2, is_active: true },
  { id: '', code: 'LA_03', text: 'Which visual pattern best represents how you learn new things?', type: 'visual', dimension: 'learning_agility', tier: 6, options: { images: ['visual_q4_a.svg','visual_q4_b.svg','visual_q4_c.svg','visual_q4_d.svg'], scores: [3, 1, 5, 2] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },

  // === NEW MAJOR DIMS ===

  // Emotional Intelligence (8 questions — 2 calibration)
  { id: '', code: 'EI_01', text: '[PLACEHOLDER] I can accurately identify what emotion I am feeling in a given moment.', type: 'likert', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'EI_02', text: '[PLACEHOLDER] I notice when someone\'s mood shifts even if they say nothing.', type: 'likert', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'EI_03', text: '[PLACEHOLDER] I can manage my emotional reactions even under significant pressure.', type: 'likert', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'EI_04', text: '[PLACEHOLDER] I find it difficult to stay composed when others are visibly upset.', type: 'likert', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'EI_05', text: '[PLACEHOLDER] How often do you adjust your communication style based on someone else\'s emotional state?', type: 'frequency', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 5, is_active: true },
  { id: '', code: 'EI_06', text: '[PLACEHOLDER] Which matters more to you in a conflict?', type: 'forced_choice', dimension: 'emotional_intelligence', tier: 4, options: { a: 'Establishing the correct facts of the situation', b: 'Making sure each person feels heard before resolving it' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 6, is_active: true },
  { id: '', code: 'EI_07', text: '[PLACEHOLDER] I recognize when my own emotions are influencing my judgment.', type: 'likert', dimension: 'emotional_intelligence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 7, is_active: true },
  { id: '', code: 'EI_08', text: '[PLACEHOLDER] A colleague is visibly withdrawn. You notice but they say they\'re fine. You:', type: 'situational', dimension: 'emotional_intelligence', tier: 4, options: { scenario: 'A colleague is withdrawn; they say they\'re fine.', choices: ['A: Take them at their word', 'B: Check in privately later', 'C: Bring it up in front of the group', 'D: Mention it to your manager'], scores: [2.3, 5, 1, 3.7] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 8, is_active: true },

  // Decision Making (8 questions — 2 calibration)
  { id: '', code: 'DM_01', text: '[PLACEHOLDER] I make decisions confidently even when information is incomplete.', type: 'likert', dimension: 'decision_making', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'DM_02', text: '[PLACEHOLDER] I often second-guess decisions I have already made.', type: 'likert', dimension: 'decision_making', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'DM_03', text: '[PLACEHOLDER] How often do you delay a decision because you feel you need more data?', type: 'frequency', dimension: 'decision_making', tier: 2, options: { labels: ['Almost Always','Usually','Rarely','Almost Never'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'DM_04', text: '[PLACEHOLDER] When I am wrong about a decision, I recognize it quickly.', type: 'likert', dimension: 'decision_making', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'DM_05', text: '[PLACEHOLDER] I find it harder to decide when no option is clearly correct.', type: 'likert', dimension: 'decision_making', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 5, is_active: true },
  { id: '', code: 'DM_06', text: '[PLACEHOLDER] Which approach do you prefer?', type: 'forced_choice', dimension: 'decision_making', tier: 2, options: { a: 'Gather more data until you\'re highly confident', b: 'Decide with 70% confidence and adjust as you learn' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 6, is_active: true },
  { id: '', code: 'DM_07', text: '[PLACEHOLDER] I commit to a path and resist the urge to revisit it unnecessarily.', type: 'likert', dimension: 'decision_making', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 7, is_active: true },
  { id: '', code: 'DM_08', text: '[PLACEHOLDER] Two strategies are equally viable. The team needs a decision in 5 minutes. You:', type: 'timed', dimension: 'decision_making', tier: 2, options: { scenario: 'Two equally viable strategies; need a decision in 5 minutes.', choices: ['A: Pick one and commit', 'B: Ask for 30 more minutes', 'C: Choose the safer option', 'D: Split the approach'], scores: [5, 1, 2.3, 3.7] }, weight: 1.3, reverse_scored: false, calibration: false, order_index: 8, is_active: true },

  // Execution (8 questions — 2 calibration)
  { id: '', code: 'EX_01', text: '[PLACEHOLDER] I consistently follow through on commitments I make to others.', type: 'likert', dimension: 'execution', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'EX_02', text: '[PLACEHOLDER] I deliver results even when the path to completion is unclear.', type: 'likert', dimension: 'execution', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'EX_03', text: '[PLACEHOLDER] How often do projects you own get completed on time?', type: 'frequency', dimension: 'execution', tier: 3, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'EX_04', text: '[PLACEHOLDER] I get things done without needing external accountability or reminders.', type: 'likert', dimension: 'execution', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'EX_05', text: '[PLACEHOLDER] I often have good ideas but struggle to convert them into completed work.', type: 'likert', dimension: 'execution', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 5, is_active: true },
  { id: '', code: 'EX_06', text: '[PLACEHOLDER] Which describes you more accurately?', type: 'forced_choice', dimension: 'execution', tier: 3, options: { a: 'Strong at generating and starting things', b: 'Strong at finishing and delivering things' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 6, is_active: true },
  { id: '', code: 'EX_07', text: '[PLACEHOLDER] I break large projects into small concrete steps before starting.', type: 'likert', dimension: 'execution', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 7, is_active: true },
  { id: '', code: 'EX_08', text: '[PLACEHOLDER] A project you own is behind. The deadline is tomorrow. You:', type: 'situational', dimension: 'execution', tier: 3, options: { scenario: 'Project is behind, deadline is tomorrow.', choices: ['A: Work through the night to finish', 'B: Scope down to the critical deliverable and cut the rest', 'C: Communicate proactively and ask for an extension', 'D: Deliver what you have and note gaps clearly'], scores: [3.7, 5, 2.3, 1] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 8, is_active: true },

  // Managing Others (8 questions — 2 calibration)
  { id: '', code: 'MO_01', text: '[PLACEHOLDER] I enjoy coaching and developing the people who work with me.', type: 'likert', dimension: 'managing_others', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'MO_02', text: '[PLACEHOLDER] I find it natural to hold people accountable without damaging the relationship.', type: 'likert', dimension: 'managing_others', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'MO_03', text: '[PLACEHOLDER] How often do you give direct feedback when someone\'s work falls short?', type: 'frequency', dimension: 'managing_others', tier: 5, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'MO_04', text: '[PLACEHOLDER] I prefer doing work myself rather than delegating it to someone else.', type: 'likert', dimension: 'managing_others', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'MO_05', text: '[PLACEHOLDER] I adapt my management style based on the individual I am working with.', type: 'likert', dimension: 'managing_others', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 5, is_active: true },
  { id: '', code: 'MO_06', text: '[PLACEHOLDER] Which type of management work energizes you more?', type: 'forced_choice', dimension: 'managing_others', tier: 5, options: { a: 'Setting direction and strategy', b: 'Developing people and coaching' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 6, is_active: true },
  { id: '', code: 'MO_07', text: '[PLACEHOLDER] I find underperformance conversations uncomfortable to initiate.', type: 'likert', dimension: 'managing_others', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 7, is_active: true },
  { id: '', code: 'MO_08', text: '[PLACEHOLDER] A direct report repeatedly misses deadlines despite reminders. You:', type: 'situational', dimension: 'managing_others', tier: 5, options: { scenario: 'Direct report repeatedly misses deadlines despite reminders.', choices: ['A: Have a direct performance conversation and set clear consequences', 'B: Dig into the root cause — workload, skill, or motivation', 'C: Reassign the work to someone more reliable', 'D: Escalate to HR'], scores: [3.7, 5, 2.3, 1] }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 8, is_active: true },

  // === NEW MINOR DIMS ===

  // Teamwork (5 questions — 2 calibration)
  { id: '', code: 'TW_01', text: '[PLACEHOLDER] I actively adapt my working style to fit the needs of the team.', type: 'likert', dimension: 'teamwork', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'TW_02', text: '[PLACEHOLDER] I prioritize the team\'s success over my individual recognition.', type: 'likert', dimension: 'teamwork', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'TW_03', text: '[PLACEHOLDER] How often do you proactively help teammates without being asked?', type: 'frequency', dimension: 'teamwork', tier: 4, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'TW_04', text: '[PLACEHOLDER] I tend to work better independently than as part of a group.', type: 'likert', dimension: 'teamwork', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'TW_05', text: '[PLACEHOLDER] Which describes your preference?', type: 'forced_choice', dimension: 'teamwork', tier: 4, options: { a: 'Working closely and collaboratively with others throughout a project', b: 'Working independently and syncing with others at key checkpoints' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 5, is_active: true },

  // Persuasion (5 questions — 2 calibration)
  { id: '', code: 'PE_01', text: '[PLACEHOLDER] I can change someone\'s mind using logic and reasoned argument.', type: 'likert', dimension: 'persuasion', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'PE_02', text: '[PLACEHOLDER] I find it difficult to convince others when they are resistant.', type: 'likert', dimension: 'persuasion', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'PE_03', text: '[PLACEHOLDER] How often are you the one who shifts a group\'s direction in a discussion?', type: 'frequency', dimension: 'persuasion', tier: 4, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'PE_04', text: '[PLACEHOLDER] I tailor my arguments to what matters most to the specific person I am persuading.', type: 'likert', dimension: 'persuasion', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'PE_05', text: '[PLACEHOLDER] Which do you rely on more to persuade others?', type: 'forced_choice', dimension: 'persuasion', tier: 4, options: { a: 'Data, evidence, and logical argument', b: 'Stories, emotion, and relationship' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 5, is_active: true },

  // Embracing Differences (5 questions — 2 calibration)
  { id: '', code: 'ED_01', text: '[PLACEHOLDER] I actively seek out perspectives from people with very different backgrounds than mine.', type: 'likert', dimension: 'embracing_differences', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 1, is_active: true },
  { id: '', code: 'ED_02', text: '[PLACEHOLDER] I feel uncomfortable when people operate very differently from how I do.', type: 'likert', dimension: 'embracing_differences', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: true, calibration: true, order_index: 2, is_active: true },
  { id: '', code: 'ED_03', text: '[PLACEHOLDER] How often do you change your approach based on someone\'s cultural or personal background?', type: 'frequency', dimension: 'embracing_differences', tier: 4, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 3, is_active: true },
  { id: '', code: 'ED_04', text: '[PLACEHOLDER] I believe diverse teams produce better outcomes than homogeneous ones.', type: 'likert', dimension: 'embracing_differences', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: false, order_index: 4, is_active: true },
  { id: '', code: 'ED_05', text: '[PLACEHOLDER] Which would you enjoy more?', type: 'forced_choice', dimension: 'embracing_differences', tier: 4, options: { a: 'Working with a team of people who think very similarly to you', b: 'Working with a team of people with radically different backgrounds and perspectives' }, weight: 1.2, reverse_scored: false, calibration: false, order_index: 5, is_active: true },

  // === CALIBRATION BOOSTERS for existing dims (those with only 1 calibration question) ===

  // Openness — 2nd calibration
  { id: '', code: 'O_04', text: '[PLACEHOLDER] I regularly read or explore content well outside my professional area.', type: 'likert', dimension: 'openness', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // Honesty-Humility — 2nd calibration
  { id: '', code: 'HH_04', text: '[PLACEHOLDER] I will tell someone an uncomfortable truth rather than stay silent.', type: 'likert', dimension: 'honesty_humility', tier: 1, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // Executive Function — 2nd calibration
  { id: '', code: 'EF_04', text: '[PLACEHOLDER] I regularly plan my week ahead rather than responding to what comes up.', type: 'frequency', dimension: 'executive_function', tier: 2, options: { labels: ['Almost Never','Rarely','Usually','Almost Always'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // Attention Control — 2nd calibration
  { id: '', code: 'AC_04', text: '[PLACEHOLDER] I can ignore distractions and stay on task even in a noisy environment.', type: 'likert', dimension: 'attention_control', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // Systems Thinking — 2nd calibration
  { id: '', code: 'ST_04', text: '[PLACEHOLDER] When solving a problem, I naturally consider how the solution affects other parts of the system.', type: 'likert', dimension: 'systems_thinking', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // 12 existing dims that need 2nd calibration flag
  { id: '', code: 'CI_04', text: '[PLACEHOLDER] I regularly generate ideas that surprise even myself.', type: 'likert', dimension: 'creative_intelligence', tier: 2, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'AN_04', text: '[PLACEHOLDER] I need significant independence in how I approach my work to perform at my best.', type: 'likert', dimension: 'autonomy_need', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'PO_04', text: '[PLACEHOLDER] Work that lacks a meaningful purpose fails to hold my engagement over time.', type: 'likert', dimension: 'purpose_orientation', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'CD_04', text: '[PLACEHOLDER] Knowing how my performance compares to others motivates me.', type: 'likert', dimension: 'competitive_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'CN_04', text: '[PLACEHOLDER] I address interpersonal tension directly rather than hoping it resolves on its own.', type: 'likert', dimension: 'conflict_navigation', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'CS_04', text: '[PLACEHOLDER] I naturally adapt the way I communicate depending on my audience.', type: 'likert', dimension: 'communication_style', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'CO_04', text: '[PLACEHOLDER] I do my best work as part of a collaborative team rather than alone.', type: 'likert', dimension: 'collaboration_signature', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'SO_04', text: '[PLACEHOLDER] I naturally think in terms of long-term trajectories rather than immediate tasks.', type: 'likert', dimension: 'strategic_orientation', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'SG_04', text: '[PLACEHOLDER] I prefer going deep in one area over being broadly capable across many areas.', type: 'forced_choice', dimension: 'specialist_generalist', tier: 5, options: { a: 'Go deep — become world-class in one domain', b: 'Go broad — develop range across many domains' }, weight: 1.2, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'II_04', text: '[PLACEHOLDER] I frequently come up with novel solutions others haven\'t considered.', type: 'likert', dimension: 'innovation_index', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'AQ_04', text: '[PLACEHOLDER] I adjust quickly when circumstances change unexpectedly.', type: 'likert', dimension: 'adaptability_quotient', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },
  { id: '', code: 'LA_04', text: '[PLACEHOLDER] I pick up new skills noticeably faster than most people I work with.', type: 'likert', dimension: 'learning_agility', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 10, is_active: true },

  // === TIEBREAKERS (10 calibration questions) ===
  { id: '', code: 'TB_01', text: '[PLACEHOLDER] Taking significant personal risk energizes rather than intimidates me.', type: 'likert', dimension: 'risk_tolerance', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 50, is_active: true },
  { id: '', code: 'TB_02', text: '[PLACEHOLDER] I am driven by a desire to have impact beyond my immediate responsibilities.', type: 'likert', dimension: 'achievement_drive', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 51, is_active: true },
  { id: '', code: 'TB_03', text: '[PLACEHOLDER] I naturally gravitate toward taking charge in unstructured situations.', type: 'likert', dimension: 'leadership_drive', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 52, is_active: true },
  { id: '', code: 'TB_04', text: '[PLACEHOLDER] I prefer having wide latitude over how I approach my work.', type: 'likert', dimension: 'autonomy_need', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 53, is_active: true },
  { id: '', code: 'TB_05', text: '[PLACEHOLDER] I feel most motivated when my work connects to a mission I believe in.', type: 'likert', dimension: 'purpose_orientation', tier: 3, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 54, is_active: true },
  { id: '', code: 'TB_06', text: '[PLACEHOLDER] I think in terms of long-term trajectories more than immediate tasks.', type: 'likert', dimension: 'strategic_orientation', tier: 5, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 55, is_active: true },
  { id: '', code: 'TB_07', text: '[PLACEHOLDER] I can move people toward a shared goal without formal authority.', type: 'likert', dimension: 'social_influence', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 56, is_active: true },
  { id: '', code: 'TB_08', text: '[PLACEHOLDER] I tend to approach conflict directly rather than avoiding it.', type: 'likert', dimension: 'conflict_navigation', tier: 4, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 57, is_active: true },
  { id: '', code: 'TB_09', text: '[PLACEHOLDER] I regularly bounce back from setbacks faster than most people I know.', type: 'likert', dimension: 'psychological_resilience', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 58, is_active: true },
  { id: '', code: 'TB_10', text: '[PLACEHOLDER] I see failure primarily as feedback rather than a verdict on my ability.', type: 'likert', dimension: 'growth_mindset', tier: 6, options: { labels: ['Strongly Disagree','Disagree','Agree','Strongly Agree'] }, weight: 1.0, reverse_scored: false, calibration: true, order_index: 59, is_active: true },
]

// Construct pairs: same-construct question pairs for inconsistency detection
export const CONSTRUCT_PAIRS: Array<{ questionA: string; questionB: string }> = [
  { questionA: 'O_01', questionB: 'O_02' },       // openness pair
  { questionA: 'C_01', questionB: 'C_03' },       // conscientiousness pair
  { questionA: 'E_01', questionB: 'E_02' },       // extraversion pair
  { questionA: 'ES_01', questionB: 'ES_02' },     // emotional stability pair
  { questionA: 'HH_01', questionB: 'HH_02' },     // honesty-humility pair
  { questionA: 'EF_01', questionB: 'EF_02' },     // executive function pair
  { questionA: 'AC_01', questionB: 'AC_02' },     // attention control pair
  { questionA: 'AN_01', questionB: 'AN_02' },     // autonomy need pair
  { questionA: 'CN_01', questionB: 'CN_03' },     // conflict navigation pair
  { questionA: 'CS_01', questionB: 'CS_02' },     // communication style pair
  { questionA: 'CO_01', questionB: 'CO_03' },     // collaboration pair
  { questionA: 'SG_01', questionB: 'SG_02' },     // specialist-generalist pair
  { questionA: 'GM_01', questionB: 'GM_03' },     // growth mindset pair
]

// Calibration coverage: 29 dimensions × 1 base question + 11 high-priority extras = 40 total calibration questions.
// All calibration flags are already set in the array above.
